### ISSUE TITLE
Basic Menu Example Code doesn't match up with the demo

### ISSUE THREAD

**Issue by graysonkent** [driftyco/ionic-preview-app#106]
It looks like the example code and the demo are out of sync. See attached picture. Maybe it failed on b0efba173dbe95c8c9ae5569ab6e8d352ca75853 ? 

![ionmenu](https://cloud.githubusercontent.com/assets/11469730/25746047/aa8b744e-316f-11e7-870d-83cd37c72c65.PNG)

**Comment by graysonkent** [comment]
Actually, pretty much every example doesn't match up and the "Improve this doc" link doesn't work. Would you guys accept a patch if I write one? Or do you know what's wrong already?

**Comment by brandyscarney** [comment]
Thanks for the issue! Having the docs & demos match all of the time has been an ongoing issue for us. In my opinion I'd like the demo code to match to a certain extent, but not be overwhelming to the user. For example, we have the demo for badge here: http://ionicframework.com/docs/components/#badges

I wouldn't want to display all of the markup that makes up that demo, since it is shows a way to use badges inside of a card, but the other markup is not needed to add a badge component.

Eventually we want the code that is displayed alongside the component demos to be in this repository, which would make it easy to keep them in sync. 

If you'd like to submit a PR to update the demos that would be helpful. Adding @mhartington and @perrygovier for feedback.

**Comment by brandyscarney** [comment]
Updated my comment. I said a PR to update the demos but I meant the docs. I think the demos are good. 🙂

**Comment by brandyscarney** [comment]
This issue was moved to driftyco/ionic-site#1095

**Comment by brandyscarney** [comment]
I moved this issue over to the ionic-site repository since it deals with updating the documentation and not necessarily the demos. :)
