### ISSUE TITLE
The menu example

### ISSUE THREAD

**Issue by larssn** [driftyco/ionic-preview-app#56]
I've noticed that your menu example code doesn't actually use `<ion-menu>` anywhere. So its kinda hard to understand it.

I'm talking about these: https://github.com/driftyco/ionic-preview-app/tree/master/app/pages/menus/basic

**Comment by brandyscarney** [comment]
Each page in the preview app is a different demo. The menu wraps all of the pages: https://github.com/driftyco/ionic-preview-app/blob/master/app/app.html#L6

and it is disabled for any pages that don't use it: https://github.com/driftyco/ionic-preview-app/blob/master/app/app.ts#L77

The preview app isn't really a "typical" app since it is used for the component demos. If you'd like a better example of a menu check out the conference app: https://github.com/driftyco/ionic-conference-app

**Comment by larssn** [comment]
Thanks, I'll check it out.
