### ISSUE TITLE
http://localhost:8100/build/js/app.bundle.js Failed to load resource: the server responded with a status of 404 (Not Found)

### ISSUE THREAD

**Issue by evandrojr** [driftyco/ionic-preview-app#8]
Hi guys!

I'm getting this error after ionic serve

http://localhost:8100/build/js/app.bundle.js Failed to load resource: the server responded with a status of 404 (Not Found)

Any hints?
-> node -v
v5.6.0

**Comment by evandrojr** [comment]
I got a blank screen for my android when I tried ionic run.

**Comment by mmehmetAliIzci** [comment]
@evandrojr My friend, since ionic's structure is change (as it mentioned here https://forum.ionicframework.com/t/attention-upcoming-ionic-2-starter-changes/45058) You need to do some changes.

First update the ionic -> **npm install -g ionic@beta**
Then **update** all npm packages 

Then create new app -> **ionic start cutePuppyPics --v2**

You will see that there is gulp file and some changes in the project.

So You have to search & replace all "**ionic-framework/ionic**" -> "**ionic-angular**"
Also copy "**ionic.config.js**" from **cutePuppyPics** and paste to your **own** ionic project.

I may forget something aswell but that is all I remember

**Comment by evandrojr** [comment]
Dear @mmehmetAliIzci It is working now!

Thank you very much for your help!

I am wondering the reason the typescript files are using .js extension. 

I also heard read they are moving to browsefy but cutePuppyPics is using webpack.

Thanks again!
